### ISSUE TITLE
Why is the mask not used in FNO?

### ISSUE THREAD

**Issue by hanbinloop** [luo-yining/CFDBench#3]
https://github.com/luo-yining/CFDBench/blob/88ec058ac6e9b1003ba4fb46ea13654888bc538c/src/models/fno/fno2d.py#L168C10-L168C10

**Comment by chen-yingfa** [comment]
Thank you for this notification, this is a bug, and we have now updated the code to address this.

### Implications of this bug on the experimental results

We expect that this bug only has a meaningful impact on the results of the GEO subset for the dam and cylinder flow problems because all other problems/subsets have constant masks. We will re-run all experiments for FNO within the next few days and documentation and the paper will be updated as soon as possible. We are sorry for the confusion caused by this.
